version: "3.8"
services:
    #php service
    php:
        container_name: pars_php
        build:
            context: .
            target: pars_php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8004:8000
        depends_on:
            - database
    # Database Server
    database:
        container_name: pars_database
        image: mysql:8.0
        ports:
            - 3300:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
    # Redis Server
    redis:
        container_name: pars_redis
        image: redis:alpine
        command: redis-server --appendonly yes
        ports:
            - 6380:6379
volumes:
    db-data: ~
